"""Core utilities and infrastructure."""

from .exceptions import (
    AuthenticationError,
    AuthorizationError,
    CacheError,
    CircularReferenceError,
    ConflictError,
    DuplicateNameError,
    ExternalFetchError,
    InvalidConfigError,
    InvalidURLError,
    NestingTooDeepError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ServiceUnavailableError,
    SourceNotFoundError,
    SubscriptionNotFoundError,
    TimeoutError,
    TooManyConfigsError,
    TooManySourcesError,
    TooManySubscriptionsError,
    ValidationError,
    VPNAPIError,
    get_exception_for_status,
)
from .retry import CircuitBreakerConfig, CircuitState, RetryConfig

__all__ = [
    "AuthenticationError",
    "AuthorizationError",
    "CacheError",
    "CircuitBreakerConfig",
    "CircuitState",
    "CircularReferenceError",
    "ConflictError",
    "DuplicateNameError",
    "ExternalFetchError",
    "InvalidConfigError",
    "InvalidURLError",
    "NestingTooDeepError",
    "NetworkError",
    "NotFoundError",
    "RateLimitError",
    "RetryConfig",
    "ServerError",
    "ServiceUnavailableError",
    "SourceNotFoundError",
    "SubscriptionNotFoundError",
    "TimeoutError",
    "TooManyConfigsError",
    "TooManySourcesError",
    "TooManySubscriptionsError",
    "VPNAPIError",
    "ValidationError",
    "get_exception_for_status",
]
